[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/2 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  02:29:51Z

App            Version  Status       Scale  Charm          Channel      Rev  Address         Exposed  Message
application             active           1  application                   0  10.152.183.37   no       
mongodb-k8s             maintenance      3  mongodb-k8s                   0  10.152.183.228  no       backup started/running, backup id:'2024-10-11T02:29:46Z'
s3-integrator           active           1  s3-integrator  latest/edge   65  10.152.183.134  no       

Unit              Workload     Agent  Address       Ports  Message
application/0*    active       idle   10.1.139.210         
mongodb-k8s/0*    maintenance  idle   10.1.139.205         backup started/running, backup id:'2024-10-11T02:29:46Z'
mongodb-k8s/1     active       idle   10.1.139.208         
mongodb-k8s/2     active       idle   10.1.139.207         
s3-integrator/0*  active       idle   10.1.139.209         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-new-mongodb-aws-1: 02:13:33 ERROR unit.new-mongodb-aws/1.juju-log new-mongodb-aws/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 670889cc2c063f24ea010ffe, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-aws-1.new-mongodb-aws-endpoints', 27017) server_type: RSGhost, rtt: 0.0019564310000532714>]>
controller-0: 02:14:48 ERROR juju.worker.caasapplicationprovisioner.runner exited "new-mongodb-aws": finding filesystem info for new-mongodb-aws-mongodb-logs-a961b0c2: unable to get persistent volume claim: k8s: persistentvolumeclaims "new-mongodb-aws-mongodb-logs-a961b0c2-new-mongodb-aws-0" not found
unit-new-mongodb-gcp-1: 02:27:22 ERROR unit.new-mongodb-gcp/1.juju-log new-mongodb-gcp/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 67088d098b3d9299bc42333c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-gcp-1.new-mongodb-gcp-endpoints', 27017) server_type: RSGhost, rtt: 0.0009419250000064494>]>
unit-new-mongodb-gcp-2: 02:27:23 ERROR unit.new-mongodb-gcp/2.juju-log new-mongodb-gcp/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 67088d0a33962f3f8bc09252, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-gcp-2.new-mongodb-gcp-endpoints', 27017) server_type: RSGhost, rtt: 0.000827299000320636>]>
controller-0: 02:28:37 ERROR juju.worker.caasapplicationprovisioner.runner exited "new-mongodb-gcp": finding filesystem info for new-mongodb-gcp-mongodb-a4f5f513: unable to get persistent volume claim: k8s: persistentvolumeclaims "new-mongodb-gcp-mongodb-a4f5f513-new-mongodb-gcp-2" not found

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...