[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-155
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  shard-two/0 [idle] active: Primary
  config-server/0 [idle] active: 
  config-server/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] active: 
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/1 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] blocked: Shard requires TLS to be enabled.
  shard-two/0 [idle] active: Primary
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] blocked: Shard requires TLS to be enabled.
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] maintenance: enabling TLS
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [executing] maintenance: enabling TLS
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: Primary
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: Primary
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: Primary
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  shard-two/0 [idle] active: Primary
  config-server/0 [executing] active: 
  config-server/1 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: Primary
  shard-one/1 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/2 [idle] active: 
  shard-two/0 [idle] active: Primary
  config-server/0 [idle] active: 
  config-server/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/1 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/2 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-two/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  config-server/0 [executing] active: 
  config-server/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/1 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/2 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-two/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  config-server/0 [executing] active: 
  config-server/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] active: 
  config-server/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  02:20:02Z

App                                Version  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
config-server                               active       2  mongodb-k8s                                3  10.152.183.240  no       Primary
self-signed-certificates                    active       1  self-signed-certificates  latest/stable  155  10.152.183.89   no       
self-signed-certificates-separate           active       1  self-signed-certificates  latest/stable  155  10.152.183.35   no       
shard-one                                   waiting      3  mongodb-k8s                                4  10.152.183.228  no       installing agent
shard-two                                   waiting      1  mongodb-k8s                                5  10.152.183.49   no       installing agent

Unit                                  Workload  Agent  Address      Ports  Message
config-server/0*                      active    idle   10.1.227.33         Primary
config-server/1                       active    idle   10.1.227.34         
self-signed-certificates-separate/0*  active    idle   10.1.227.47         
self-signed-certificates/0*           active    idle   10.1.227.26         
shard-one/0*                          blocked   idle   10.1.227.41         Shard CA and Config-Server CA don't match.
shard-one/1                           blocked   idle   10.1.227.45         Shard CA and Config-Server CA don't match.
shard-one/2                           blocked   idle   10.1.227.44         Shard CA and Config-Server CA don't match.
shard-two/0*                          blocked   idle   10.1.227.46         Shard CA and Config-Server CA don't match.

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-1: 01:33:28 ERROR unit.config-server/1.juju-log database-peers:0: Failed to create the operator user: non-zero exit code 1 executing ['/usr/bin/mongosh', 'mongodb://localhost/admin', '--quiet', '--eval', "db.createUser({  user: 'operator',  pwd: passwordPrompt(),  roles:[    {'role': 'userAdminAnyDatabase', 'db': 'admin'},     {'role': 'readWriteAnyDatabase', 'db': 'admin'},     {'role': 'clusterAdmin', 'db': 'admin'},   ],  mechanisms: ['SCRAM-SHA-256'],  passwordDigestor: 'server',})"], stdout='Enter password\n********************************', stderr='MongoServerError: not primary\n'
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-config-server-1/charm/./src/charm.py", line 926, in _init_operator_user
    process.wait_output()
  File "/var/lib/juju/agents/unit-config-server-1/charm/venv/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mongosh', 'mongodb://localhost/admin', '--quiet', '--eval', "db.createUser({  user: 'operator',  pwd: passwordPrompt(),  roles:[    {'role': 'userAdminAnyDatabase', 'db': 'admin'},     {'role': 'readWriteAnyDatabase', 'db': 'admin'},     {'role': 'clusterAdmin', 'db': 'admin'},   ],  mechanisms: ['SCRAM-SHA-256'],  passwordDigestor: 'server',})"], stdout='Enter password\n********************************', stderr='MongoServerError: not primary\n'
unit-config-server-1: 01:33:34 ERROR unit.config-server/1.juju-log database-peers:0: Failed to create the operator user: non-zero exit code 1 executing ['/usr/bin/mongosh', 'mongodb://localhost/admin', '--quiet', '--eval', "db.createUser({  user: 'operator',  pwd: passwordPrompt(),  roles:[    {'role': 'userAdminAnyDatabase', 'db': 'admin'},     {'role': 'readWriteAnyDatabase', 'db': 'admin'},     {'role': 'clusterAdmin', 'db': 'admin'},   ],  mechanisms: ['SCRAM-SHA-256'],  passwordDigestor: 'server',})"], stdout='Enter password\n********************************', stderr='MongoServerError: not primary\n'
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-config-server-1/charm/./src/charm.py", line 926, in _init_operator_user
    process.wait_output()
  File "/var/lib/juju/agents/unit-config-server-1/charm/venv/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mongosh', 'mongodb://localhost/admin', '--quiet', '--eval', "db.createUser({  user: 'operator',  pwd: passwordPrompt(),  roles:[    {'role': 'userAdminAnyDatabase', 'db': 'admin'},     {'role': 'readWriteAnyDatabase', 'db': 'admin'},     {'role': 'clusterAdmin', 'db': 'admin'},   ],  mechanisms: ['SCRAM-SHA-256'],  passwordDigestor: 'server',})"], stdout='Enter password\n********************************', stderr='MongoServerError: not primary\n'
unit-config-server-1: 01:35:07 ERROR unit.config-server/1.juju-log config-server:3: Failed to add shard shard-one to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1724376905, 3), 'signature': {'hash': b'\\xed\\x0f\\xc1\\t\\xa5\\rU\\xa4\\x11PF\\xc3\\xd5C\\x9c\\x98\\x94Y\\x8e\\t', 'keyId': 7406142043585511448}}, 'operationTime': Timestamp(1724376905, 3)}")
unit-config-server-1: 01:35:07 ERROR unit.config-server/1.juju-log config-server:3: shard-one shard does not have the same auth as the config server.
unit-config-server-1: 01:35:08 ERROR unit.config-server/1.juju-log config-server:4: Failed to add shard shard-two to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1724376907, 1), 'signature': {'hash': b'ay\\xe5e\\xb8w\\xcfd\\x92\\x08q9;V\\xb2\\x88\\xa1\\xccS`', 'keyId': 7406142043585511448}}, 'operationTime': Timestamp(1724376907, 1)}")
unit-config-server-1: 01:35:23 ERROR unit.config-server/1.juju-log config-server:4: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724376922, 1), \'signature\': {\'hash\': b\'B\\r\\xe7y\\x89\\t\\x9f>b\\xa08\\x8doE\\x05f5\\xa99P\', \'keyId\': 7406142043585511448}}, \'operationTime\': Timestamp(1724376922, 1)}')
unit-config-server-1: 01:35:23 ERROR unit.config-server/1.juju-log config-server:4: Failed to add shard-one to cluster
unit-config-server-1: 01:35:23 ERROR unit.config-server/1.juju-log config-server:4: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724376922, 1), \'signature\': {\'hash\': b\'B\\r\\xe7y\\x89\\t\\x9f>b\\xa08\\x8doE\\x05f5\\xa99P\', \'keyId\': 7406142043585511448}}, \'operationTime\': Timestamp(1724376922, 1)}')
unit-config-server-1: 01:35:24 ERROR unit.config-server/1.juju-log config-server:3: Failed to add shard shard-two to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1724376924, 2), 'signature': {'hash': b'\\xce\\x86\\xec\\xe7\\xff\\x11w\\xc7x{ILz\\xb0/\\xff\\xc3\\x14W\\xbd', 'keyId': 7406142043585511448}}, 'operationTime': Timestamp(1724376924, 2)}")
unit-config-server-1: 01:35:25 ERROR unit.config-server/1.juju-log config-server:3: shard-two shard does not have the same auth as the config server.
unit-shard-one-2: 01:40:07 ERROR unit.shard-one/2.juju-log certificates:5: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 01:40:07 ERROR unit.shard-one/0.juju-log certificates:5: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 01:40:07 ERROR unit.config-server/0.juju-log certificates:7: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 01:40:07 ERROR unit.config-server/1.juju-log certificates:7: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-two-0: 01:40:08 ERROR unit.shard-two/0.juju-log certificates:6: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 01:40:08 ERROR unit.shard-one/2.juju-log certificates:5: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-1: 01:40:08 ERROR unit.shard-one/1.juju-log certificates:5: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 01:40:08 ERROR unit.shard-one/0.juju-log certificates:5: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-two-0: 01:40:08 ERROR unit.shard-two/0.juju-log certificates:6: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 01:40:08 ERROR unit.config-server/1.juju-log certificates:7: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:40:08 ERROR unit.config-server/0.juju-log certificates:7: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-1: 01:40:08 ERROR unit.shard-one/1.juju-log certificates:5: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:40:19 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:40:19 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:40:33 ERROR unit.config-server/0.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:40:33 ERROR unit.config-server/0.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:40:43 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:40:43 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-shard-one-0: 01:41:21 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7e8c0b75fd9b5b6a378b1, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0008852600000182065>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0011353339999686796>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0011909979999700226>]>
unit-shard-one-0: 01:41:24 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7e8c259f51214962cfde8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.002535868999984814>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=NotPrimaryError('The server is in quiesce mode and will shut down, full error: {\'topologyVersion\': {\'processId\': ObjectId(\'66c7e8bb2a0a8b6676fd7d59\'), \'counter\': 4}, \'ok\': 0.0, \'errmsg\': \'The server is in quiesce mode and will shut down\', \'code\': 91, \'codeName\': \'ShutdownInProgress\', \'remainingQuiesceTimeMillis\': 12915, \'lastCommittedOpTime\': Timestamp(0, 0), \'$clusterTime\': {\'clusterTime\': Timestamp(1724377277, 5), \'signature\': {\'hash\': b\'\\x03\\xdf\\x1f"eH@\\x022\\xc9e:^\\x9cc\\xcdA\\xe6\\xf8q\', \'keyId\': 7406142043585511448}}, \'operationTime\': Timestamp(1724377214, 3)}')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0022953779999852486>]>
unit-shard-one-0: 01:41:26 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7e8c5daa6b552b6b4ca7e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.000514153999915834>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=NotPrimaryError('The server is in quiesce mode and will shut down, full error: {\'topologyVersion\': {\'processId\': ObjectId(\'66c7e8bb2a0a8b6676fd7d59\'), \'counter\': 4}, \'ok\': 0.0, \'errmsg\': \'The server is in quiesce mode and will shut down\', \'code\': 91, \'codeName\': \'ShutdownInProgress\', \'remainingQuiesceTimeMillis\': 10385, \'lastCommittedOpTime\': Timestamp(0, 0), \'$clusterTime\': {\'clusterTime\': Timestamp(1724377277, 5), \'signature\': {\'hash\': b\'\\x03\\xdf\\x1f"eH@\\x022\\xc9e:^\\x9cc\\xcdA\\xe6\\xf8q\', \'keyId\': 7406142043585511448}}, \'operationTime\': Timestamp(1724377214, 3)}')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0004249219999792331>]>
unit-shard-one-0: 01:42:39 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:42:39 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:42:41 ERROR unit.shard-one/1.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:42:41 ERROR unit.shard-one/1.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:42:59 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:43:00 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-2: 01:43:01 ERROR unit.shard-one/2.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-2: 01:43:01 ERROR unit.shard-one/2.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:43:02 ERROR unit.shard-one/1.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:43:02 ERROR unit.shard-one/1.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:43:19 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:43:19 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-two-0: 01:45:07 ERROR unit.shard-two/0.juju-log certificates:6: An unknown certificate is available -- ignoring.
unit-shard-two-0: 01:45:07 ERROR unit.shard-two/0.juju-log certificates:6: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:46:47 ERROR unit.config-server/0.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:46:47 ERROR unit.config-server/0.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:46:47 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:46:47 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 01:46:48 ERROR unit.config-server/1.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:46:48 ERROR unit.config-server/1.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:46:50 ERROR unit.config-server/1.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:46:50 ERROR unit.config-server/1.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:47:06 ERROR unit.config-server/0.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:47:07 ERROR unit.config-server/0.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:47:14 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:47:14 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:49:41 ERROR unit.config-server/0.juju-log certificates:7: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:49:41 ERROR unit.config-server/0.juju-log certificates:7: This operation (delete_relation_data()) can only be performed by the leader unit
unit-shard-two-0: 01:49:51 ERROR unit.shard-two/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/pool.py", line 989, in command
    return command(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/network.py", line 202, in command
    reply = receive_message(conn, request_id)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/network.py", line 317, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/network.py", line 408, in _receive_data_on_socket
    raise OSError("connection closed")
OSError: connection closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1555, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 851, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1359, in _connect_pbm_agent
    self.has_config_server() and self.shard._is_added_to_cluster()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 1102, in _is_added_to_cluster
    cluster_shards = self.get_shard_members()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 1151, in get_shard_members
    return mongo.get_shard_members()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/mongos.py", line 158, in get_shard_members
    shard_list = self.client.admin.command("listShards")
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/database.py", line 897, in command
    return self._command(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/database.py", line 737, in _command
    return conn.command(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/helpers.py", line 342, in inner
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/pool.py", line 1017, in command
    self._raise_connection_failure(error)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/pool.py", line 1214, in _raise_connection_failure
    _raise_connection_failure(self.address, error, timeout_details=details)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/pool.py", line 427, in _raise_connection_failure
    raise AutoReconnect(msg) from error
pymongo.errors.AutoReconnect: config-server-1.config-server-endpoints:27018: connection closed (configured timeouts: connectTimeoutMS: 2000.0ms)
unit-shard-two-0: 01:49:52 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:49:57 ERROR unit.shard-one/0.juju-log Unable to access primary due to: shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7eac443307ccea36d8b9b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-config-server-1: 01:49:59 ERROR unit.config-server/1.juju-log config-server:3: Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7eac6977f0627a1ee4c5b, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-shard-two-0: 01:50:01 ERROR unit.shard-two/0.juju-log Unable to access primary due to: shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7eac8f15f3c4e90f1f36e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-two-0.shard-two-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-config-server-1: 01:50:02 ERROR unit.config-server/1.juju-log Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7eac9d08da62e7044b9cc, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-shard-two-0: 01:50:04 ERROR unit.shard-two/0.juju-log Unable to access primary due to: shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7eacbc7abb47a5b53c504, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-two-0.shard-two-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-config-server-1: 01:50:04 ERROR unit.config-server/1.juju-log config-server:4: Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7eacbe051248a7ecb0d4a, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-config-server-1: 01:50:06 ERROR unit.config-server/1.juju-log config-server:4: Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7eacde051248a7ecb0d4b, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-shard-two-0: 01:50:09 ERROR unit.shard-two/0.juju-log sharding:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 3187, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-shard-two-0/secret-get', '--label', 'sharding.4.extra.secret', '--refresh', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 3552, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 3189, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR consumer label "sharding.4.extra.secret" not found


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1555, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 516, in _emit
    self.framework.reemit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 870, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 610, in _handle_changed_secrets
    (operator_password, backup_password) = self.get_cluster_passwords(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 651, in get_cluster_passwords
    operator_password = self.database_requires.fetch_relation_field(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1350, in fetch_relation_field
    self.fetch_relation_data([relation_id], [field], relation_name)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1342, in fetch_relation_data
    data[relation.id] = self._fetch_specific_relation_data(relation, fields)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1818, in _fetch_specific_relation_data
    return self._fetch_relation_data_with_secrets(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1242, in _fetch_relation_data_with_secrets
    result, normal_fields = self._process_secret_fields(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1186, in _process_secret_fields
    if group_result := operation(relation, group, secret_fields, *args, **kwargs):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1120, in _get_group_secret_contents
    secret_data := secret.get_content()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 746, in get_content
    self._secret_content = self.meta.get_content(refresh=True)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 1392, in get_content
    self._content = self._backend.secret_get(id=self.id, label=self.label, refresh=refresh)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 3555, in secret_get
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError
unit-shard-two-0: 01:50:09 ERROR juju.worker.uniter.operation hook "sharding-relation-departed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:50:10 ERROR unit.shard-one/0.juju-log database-peers:1: Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7ead1a21b9adc8eeb2cff, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.005610445999991498>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.009758007000073121>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.003944710000041596>]>
unit-shard-one-0: 01:50:14 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7ead59be4e42afa818477, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0022061399999984133>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.012195137999924555>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.015006804999984524>]>
unit-config-server-0: 01:50:17 ERROR unit.config-server/0.juju-log config-server/0.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7ead8ee3c24a10d238e55, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27017) server_type: RSGhost, rtt: 0.0006535470001836075>]>
controller-0: 01:51:24 ERROR juju.worker.caasapplicationprovisioner.runner exited "config-server": finding filesystem info for config-server-mongodb-98959c88: unable to get persistent volume claim: k8s: persistentvolumeclaims "config-server-mongodb-98959c88-config-server-1" not found
unit-shard-one-0: 01:53:05 ERROR unit.shard-one/0.juju-log certificates:11: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-1: 01:53:05 ERROR unit.shard-one/1.juju-log certificates:11: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 01:53:05 ERROR unit.config-server/0.juju-log certificates:13: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 01:53:05 ERROR unit.shard-one/2.juju-log certificates:11: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 01:53:05 ERROR unit.config-server/1.juju-log certificates:13: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 01:53:06 ERROR unit.shard-one/0.juju-log certificates:11: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-2: 01:53:06 ERROR unit.shard-one/2.juju-log certificates:11: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 01:53:06 ERROR unit.config-server/1.juju-log certificates:13: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:53:06 ERROR unit.config-server/0.juju-log certificates:13: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-two-0: 01:53:06 ERROR unit.shard-two/0.juju-log certificates:12: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-1: 01:53:06 ERROR unit.shard-one/1.juju-log certificates:11: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-two-0: 01:53:06 ERROR unit.shard-two/0.juju-log certificates:12: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:54:26 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=b3e5560d-fec7-4874-910f-f0fb87f308eb,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=b3e5560d-fec7-4874-910f-f0fb87f308eb,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724378066, 2), \'signature\': {\'hash\': b\'\\xf0\\xd5\\x00\\xde.8c~\\xe9\\xa4\\x86\\x82\\xc6VuH\\xef.\\xb0Y\', \'keyId\': 7406146810999210009}}, \'operationTime\': Timestamp(1724378066, 2)}')
unit-config-server-0: 01:54:26 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard-one to cluster
unit-config-server-0: 01:54:26 ERROR unit.config-server/0.juju-log config-server:14: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=b3e5560d-fec7-4874-910f-f0fb87f308eb,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=b3e5560d-fec7-4874-910f-f0fb87f308eb,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724378066, 2), \'signature\': {\'hash\': b\'\\xf0\\xd5\\x00\\xde.8c~\\xe9\\xa4\\x86\\x82\\xc6VuH\\xef.\\xb0Y\', \'keyId\': 7406146810999210009}}, \'operationTime\': Timestamp(1724378066, 2)}')
unit-config-server-0: 01:54:43 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724378082, 2), \'signature\': {\'hash\': b\'@\\xaa\\xc7H\\x17d\\xa8\\x1d\\xa5\\xf9\\xd0\\x07\\x92wg\\x90\\x9a\\xa7M\\xf6\', \'keyId\': 7406146810999210009}}, \'operationTime\': Timestamp(1724378082, 2)}')
unit-config-server-0: 01:54:43 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard-one to cluster
unit-config-server-0: 01:54:43 ERROR unit.config-server/0.juju-log config-server:14: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724378082, 2), \'signature\': {\'hash\': b\'@\\xaa\\xc7H\\x17d\\xa8\\x1d\\xa5\\xf9\\xd0\\x07\\x92wg\\x90\\x9a\\xa7M\\xf6\', \'keyId\': 7406146810999210009}}, \'operationTime\': Timestamp(1724378082, 2)}')
unit-shard-one-2: 01:54:45 ERROR unit.shard-one/2.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-2: 01:54:45 ERROR unit.shard-one/2.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:54:46 ERROR unit.shard-one/1.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:54:46 ERROR unit.shard-one/1.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:54:47 ERROR unit.shard-one/0.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:54:47 ERROR unit.shard-one/0.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:55:00 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724378100, 3), \'signature\': {\'hash\': b\'#cY\\xd9,\\x93\\xf4\\xd8^4\\x81\\xc8)\\x0fh\\x18A"\\x8d7\', \'keyId\': 7406146810999210009}}, \'operationTime\': Timestamp(1724378100, 3)}')
unit-config-server-0: 01:55:00 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard-one to cluster
unit-config-server-0: 01:55:00 ERROR unit.config-server/0.juju-log config-server:14: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724378100, 3), \'signature\': {\'hash\': b\'#cY\\xd9,\\x93\\xf4\\xd8^4\\x81\\xc8)\\x0fh\\x18A"\\x8d7\', \'keyId\': 7406146810999210009}}, \'operationTime\': Timestamp(1724378100, 3)}')
unit-config-server-0: 01:55:14 ERROR unit.config-server/0.juju-log config-server:15: Failed to add shard shard-two to the config server, error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=b3e5560d-fec7-4874-910f-f0fb87f308eb,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=b3e5560d-fec7-4874-910f-f0fb87f308eb,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724378112, 2), \'signature\': {\'hash\': b\'\\x08\\r\\xf0O\\x9fX\\xdd\\x83qw\\x99\\x01\\xa4H\\xe2\\xabXj\\xcaF\', \'keyId\': 7406146810999210009}}, \'operationTime\': Timestamp(1724378112, 2)}')
unit-config-server-0: 01:55:14 ERROR unit.config-server/0.juju-log config-server:15: Failed to add shard-two to cluster
unit-config-server-0: 01:55:14 ERROR unit.config-server/0.juju-log config-server:15: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=b3e5560d-fec7-4874-910f-f0fb87f308eb,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=b3e5560d-fec7-4874-910f-f0fb87f308eb,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1724378112, 2), \'signature\': {\'hash\': b\'\\x08\\r\\xf0O\\x9fX\\xdd\\x83qw\\x99\\x01\\xa4H\\xe2\\xabXj\\xcaF\', \'keyId\': 7406146810999210009}}, \'operationTime\': Timestamp(1724378112, 2)}')
unit-shard-two-0: 01:55:25 ERROR unit.shard-two/0.juju-log certificates:12: An unknown certificate is available -- ignoring.
unit-shard-two-0: 01:55:25 ERROR unit.shard-two/0.juju-log certificates:12: An unknown certificate is available -- ignoring.
unit-self-signed-certificates-0: 02:00:23 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "7c079604-1a4d-43d2-85d3-93a319ec8190:r#11#shard-one": settings 7c079604-1a4d-43d2-85d3-93a319ec8190:r#11#shard-one not found (not found)
unit-shard-one-1: 02:00:24 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "7c079604-1a4d-43d2-85d3-93a319ec8190:r#11#self-signed-certificates": settings 7c079604-1a4d-43d2-85d3-93a319ec8190:r#11#self-signed-certificates not found (not found)
unit-shard-one-0: 02:06:19 ERROR unit.shard-one/0.juju-log certificates:16: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 02:06:19 ERROR unit.shard-one/0.juju-log certificates:16: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-2: 02:06:28 ERROR unit.shard-one/2.juju-log certificates:16: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 02:06:28 ERROR unit.shard-one/2.juju-log certificates:16: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-1: 02:10:52 ERROR unit.shard-one/1.juju-log certificates:16: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-1: 02:10:52 ERROR unit.shard-one/1.juju-log certificates:16: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 02:15:43 ERROR unit.config-server/1.juju-log certificates:13: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:15:43 ERROR unit.config-server/1.juju-log certificates:13: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-0: 02:16:02 ERROR unit.config-server/0.juju-log config-server:14: Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7f0e145a21d70c1b353db, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-config-server-0: 02:16:04 ERROR unit.config-server/0.juju-log Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 66c7f0e399ec185429cf128c, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-config-server-1: 02:17:35 ERROR unit.config-server/1.juju-log certificates:17: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 02:17:35 ERROR unit.config-server/1.juju-log certificates:17: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 02:17:36 ERROR unit.config-server/0.juju-log certificates:17: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 02:17:36 ERROR unit.config-server/0.juju-log certificates:17: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 02:17:37 ERROR unit.config-server/1.juju-log certificates:17: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:17:37 ERROR unit.config-server/1.juju-log certificates:17: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:17:52 ERROR unit.config-server/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:17:52 ERROR unit.config-server/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:18:04 ERROR unit.config-server/1.juju-log certificates:17: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:18:04 ERROR unit.config-server/1.juju-log certificates:17: This operation (update_relation_data()) can only be performed by the leader unit
unit-shard-one-0: 02:19:46 ERROR unit.shard-one/0.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-shard-one-2: 02:19:58 ERROR unit.shard-one/2.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-shard-one-1: 02:19:58 ERROR unit.shard-one/1.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-shard-two-0: 02:19:58 ERROR unit.shard-two/0.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...