[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/1, False
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/1. Target unit name: mongodb-k8s/1, True
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:648 Result of isolating unit from cluster is 'b'networkchaos.chaos-mesh.org/network-loss-primary created\n''
[32mINFO    [0m integration.ha_tests.test_ha:test_ha.py:568 Primary instance mongodb-k8s/1 isolated from cluster
[32mINFO    [0m integration.ha_tests.test_ha:test_ha.py:573 Waiting until Mongodb detects primary instance mongodb-k8s/1 is not reachable
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:59:44Z

App               Version  Status   Scale  Charm        Channel  Rev  Address         Exposed  Message
another-database           active       1  mongodb-k8s             1  10.152.183.219  no       Primary
application                active       1  application             0  10.152.183.239  no       
mongodb-k8s                waiting      3  mongodb-k8s             0  10.152.183.78   no       waiting for container

Unit                 Workload  Agent  Address       Ports  Message
another-database/0*  active    idle   10.1.188.156         Primary
application/0*       active    idle   10.1.188.145         
mongodb-k8s/0*       active    idle   10.1.188.153         
mongodb-k8s/1        active    idle   10.1.188.144         Primary
mongodb-k8s/2        active    idle   10.1.188.146         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-mongodb-k8s-2: 01:38:37 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 6701ea1c2d7ea8dfb9229db6, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0007102029999828119>]>

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...