[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: 
  mongodb-k8s/1 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: 
  mongodb-k8s/1 [idle] active: Primary
  mongodb-k8s/2 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  02:14:35Z

App            Version  Status       Scale  Charm          Channel      Rev  Address         Exposed  Message
application             active           1  application                   0  10.152.183.19   no       
mongodb-k8s             maintenance      3  mongodb-k8s                   0  10.152.183.183  no       backup started/running, backup id:'2024-09-27T02:14:32Z'
s3-integrator           active           1  s3-integrator  latest/edge   57  10.152.183.85   no       

Unit              Workload     Agent  Address      Ports  Message
application/0*    active       idle   10.1.193.18         
mongodb-k8s/0     active       idle   10.1.193.15         
mongodb-k8s/1*    maintenance  idle   10.1.193.14         backup started/running, backup id:'2024-09-27T02:14:32Z'
mongodb-k8s/2     active       idle   10.1.193.16         
s3-integrator/0*  active       idle   10.1.193.17         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-mongodb-k8s-0: 01:39:59 ERROR unit.mongodb-k8s/0.juju-log s3-credentials:4: Failed to get pbm status: non-zero exit code 1 executing ['/usr/bin/pbm', 'status', '-o', 'json'], stdout='{"Error":"get status of backups: get storage: storage undefined"}\n', stderr=''
unit-new-mongodb-aws-1: 01:57:32 ERROR unit.new-mongodb-aws/1.juju-log new-mongodb-aws/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66f6110afba2e2dafc539df5, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-aws-1.new-mongodb-aws-endpoints', 27017) server_type: RSGhost, rtt: 0.0008386319998407998>]>
controller-0: 01:58:47 ERROR juju.worker.caasapplicationprovisioner.runner exited "new-mongodb-aws": finding filesystem info for new-mongodb-aws-mongodb-87a3fe70: unable to get persistent volume claim: k8s: persistentvolumeclaims "new-mongodb-aws-mongodb-87a3fe70-new-mongodb-aws-2" not found
unit-new-mongodb-gcp-1: 02:12:08 ERROR unit.new-mongodb-gcp/1.juju-log new-mongodb-gcp/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66f6147766c4330afc5eb293, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-gcp-1.new-mongodb-gcp-endpoints', 27017) server_type: RSGhost, rtt: 0.0005628359999718668>]>
unit-new-mongodb-gcp-2: 02:12:09 ERROR unit.new-mongodb-gcp/2.juju-log new-mongodb-gcp/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66f61478c6811d21ab545dfe, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-gcp-2.new-mongodb-gcp-endpoints', 27017) server_type: RSGhost, rtt: 0.00046727600010854076>]>
controller-0: 02:13:21 ERROR juju.worker.caasapplicationprovisioner.runner exited "new-mongodb-gcp": finding filesystem info for new-mongodb-gcp-mongodb-logs-a3c0f6f7: unable to get persistent volume claim: k8s: persistentvolumeclaims "new-mongodb-gcp-mongodb-logs-a3c0f6f7-new-mongodb-gcp-0" not found

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...