[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  application/0 [idle] active: received database credentials of the second database
  application/1 [idle] active: received database credentials of the second database
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] active: 
  another-database/0 [idle] active: Primary
  another-database/1 [idle] active: 
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] active: 
[32mINFO    [0m integration.helpers:helpers.py:196 Running mongo command: 'mongosh --quiet --eval \'db.runCommand({ replSetGetStatus : 1 });\' "mongodb://relation-2:6V2d9ZiCxNIh5PHrTbjbtVMBNyaIIeRG@mongodb-k8s-0.mongodb-k8s-endpoints,mongodb-k8s-1.mongodb-k8s-endpoints/application_first_database?replicaSet=mongodb-k8s&authSource=admin"'
[32mINFO    [0m integration.helpers:helpers.py:438 Checking or creating helper mongo pod ...
[32mINFO    [0m integration.helpers:helpers.py:443 pod 'mongodb-helper' in namespace 'test' already exists.
[32mINFO    [0m integration.helpers:helpers.py:482 Checking pod mongodb-helper is ready...
[1m[31mERROR   [0m integration.helpers:helpers.py:224 code 1; stdout ''; stderr: 'MongoServerError: Authentication failed.\ncommand terminated with exit code 1\n'
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  01:52:03Z

App                  Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
another-application           active      1  application             1  10.152.183.135  no       received database credentials of the first database
another-database              active      2  mongodb-k8s             1  10.152.183.102  no       Primary
application                   active      2  application             0  10.152.183.149  no       received database credentials of the second database
mongodb-k8s                   active      2  mongodb-k8s             0  10.152.183.143  no       Primary

Unit                    Workload  Agent  Address       Ports  Message
another-application/0*  active    idle   10.1.223.221         received database credentials of the first database
another-database/0*     active    idle   10.1.223.212         Primary
another-database/1      active    idle   10.1.223.213         
application/0*          active    idle   10.1.223.206         received database credentials of the second database
application/1           active    idle   10.1.223.207         received database credentials of the second database
mongodb-k8s/0*          active    idle   10.1.223.204         Primary
mongodb-k8s/1           active    idle   10.1.223.205         

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-mongodb-k8s-3: 01:46:36 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66babafb7a977048396321ce, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005558320000318417>]>
unit-mongodb-k8s-2: 01:47:34 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66babb3534b68ce1f5321d62, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0007064320000154112>]>

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...