[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  application/0 [idle] active: received database credentials of the second database
  application/1 [idle] active: received database credentials of the second database
  mongodb-k8s/0 [executing] active: 
  mongodb-k8s/1 [executing] active: 
  another-database/0 [idle] active: Primary
  another-database/1 [idle] active: 
  mongodb-k8s/0 [executing] active: 
  mongodb-k8s/1 [executing] active: 
[32mINFO    [0m integration.helpers:helpers.py:196 Running mongo command: 'mongosh --quiet --eval \'db.runCommand({ replSetGetStatus : 1 });\' "mongodb://relation-2:S1zXKIVyCvutRfJXp8hYPH0EnNGm9qgu@mongodb-k8s-0.mongodb-k8s-endpoints,mongodb-k8s-1.mongodb-k8s-endpoints/application_first_database?replicaSet=mongodb-k8s&authSource=admin"'
[32mINFO    [0m integration.helpers:helpers.py:438 Checking or creating helper mongo pod ...
[32mINFO    [0m integration.helpers:helpers.py:443 pod 'mongodb-helper' in namespace 'test' already exists.
[32mINFO    [0m integration.helpers:helpers.py:482 Checking pod mongodb-helper is ready...
[31m[1mERROR   [0m integration.helpers:helpers.py:224 code 1; stdout ''; stderr: 'MongoServerError: Authentication failed.\ncommand terminated with exit code 1\n'
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  01:44:41Z

App                  Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
another-application           active      1  application             1  10.152.183.140  no       received database credentials of the first database
another-database              active      2  mongodb-k8s             1  10.152.183.230  no       Primary
application                   active      2  application             0  10.152.183.138  no       received database credentials of the second database
mongodb-k8s                   active      2  mongodb-k8s             0  10.152.183.19   no       

Unit                    Workload  Agent  Address     Ports  Message
another-application/0*  active    idle   10.1.96.93         received database credentials of the first database
another-database/0*     active    idle   10.1.96.84         Primary
another-database/1      active    idle   10.1.96.85         
application/0*          active    idle   10.1.96.79         received database credentials of the second database
application/1           active    idle   10.1.96.78         received database credentials of the second database
mongodb-k8s/0*          active    idle   10.1.96.76         
mongodb-k8s/1           active    idle   10.1.96.77         

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-mongodb-k8s-3: 01:39:21 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66bfff48da9e5379fa9b7367, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0016336659999751646>]>
unit-mongodb-k8s-2: 01:40:17 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66bfff802e592d13f8b6cdff, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005666969999538196>]>

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...