[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/2 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  02:28:50Z

App            Version  Status       Scale  Charm          Channel      Rev  Address         Exposed  Message
application             active           1  application                   0  10.152.183.207  no       
mongodb-k8s             maintenance      3  mongodb-k8s                   0  10.152.183.252  no       backup started/running, backup id:'2024-10-17T02:28:47Z'
s3-integrator           active           1  s3-integrator  latest/edge   65  10.152.183.31   no       

Unit              Workload     Agent  Address      Ports  Message
application/0*    active       idle   10.1.233.82         
mongodb-k8s/0*    maintenance  idle   10.1.233.77         backup started/running, backup id:'2024-10-17T02:28:47Z'
mongodb-k8s/1     active       idle   10.1.233.80         
mongodb-k8s/2     active       idle   10.1.233.79         
s3-integrator/0*  active       idle   10.1.233.81         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-new-mongodb-aws-1: 02:17:50 ERROR unit.new-mongodb-aws/1.juju-log new-mongodb-aws/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 671073cddb35f252303b996b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-aws-1.new-mongodb-aws-endpoints', 27017) server_type: RSGhost, rtt: 0.00046281400000225403>]>
unit-new-mongodb-aws-2: 02:17:51 ERROR unit.new-mongodb-aws/2.juju-log new-mongodb-aws/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 671073ce8f562d6100f3de36, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-aws-2.new-mongodb-aws-endpoints', 27017) server_type: RSGhost, rtt: 0.0005785710000054678>]>
controller-0: 02:19:04 ERROR juju.worker.caasapplicationprovisioner.runner exited "new-mongodb-aws": finding filesystem info for new-mongodb-aws-mongodb-97b8661b: unable to get persistent volume claim: k8s: persistentvolumeclaims "new-mongodb-aws-mongodb-97b8661b-new-mongodb-aws-2" not found
unit-new-mongodb-gcp-1: 02:26:33 ERROR unit.new-mongodb-gcp/1.juju-log new-mongodb-gcp/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 671075d87ec02af0578a6563, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('new-mongodb-gcp-1.new-mongodb-gcp-endpoints', 27017) server_type: RSGhost, rtt: 0.0010256829996251327>]>
controller-0: 02:27:46 ERROR juju.worker.caasapplicationprovisioner.runner exited "new-mongodb-gcp": finding filesystem info for new-mongodb-gcp-mongodb-logs-28a6c568: unable to get persistent volume claim: k8s: persistentvolumeclaims "new-mongodb-gcp-mongodb-logs-28a6c568-new-mongodb-gcp-0" not found

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...