[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-155
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  shard-two/0 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/1 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] blocked: Shard requires TLS to be enabled.
  shard-two/0 [idle] active: Primary
  config-server/0 [executing] blocked: shards shard-one are unreachable.
  config-server/1 [executing] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] blocked: Shard requires TLS to be enabled.
  config-server/0 [executing] blocked: shards shard-one are unreachable.
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/2 [executing] blocked: Shard requires TLS to be enabled.
  config-server/0 [executing] blocked: shards shard-one are unreachable.
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] waiting: waiting to reconfigure replica set
  shard-one/1 [executing] maintenance: enabling TLS
  shard-one/2 [executing] maintenance: enabling TLS
  config-server/0 [executing] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] active: 
  config-server/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: Primary
  shard-two/0 [idle] active: Primary
  config-server/0 [executing] active: 
  config-server/1 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: Primary
  shard-two/0 [idle] active: Primary
  config-server/0 [idle] active: 
  config-server/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] active: 
  config-server/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/1 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/2 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-two/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  config-server/0 [executing] active: 
  config-server/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/1 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/2 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-two/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  config-server/0 [executing] maintenance: enabling TLS
  config-server/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [executing] waiting: waiting to reconfigure replica set
  config-server/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  02:15:54Z

App                                Version  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
config-server                               active       2  mongodb-k8s                                3  10.152.183.29   no       Primary
self-signed-certificates                    active       1  self-signed-certificates  latest/stable  155  10.152.183.99   no       
self-signed-certificates-separate           active       1  self-signed-certificates  latest/stable  155  10.152.183.163  no       
shard-one                                   blocked      3  mongodb-k8s                                4  10.152.183.117  no       Shard CA and Config-Server CA don't match.
shard-two                                   blocked      1  mongodb-k8s                                5  10.152.183.83   no       Shard CA and Config-Server CA don't match.

Unit                                  Workload  Agent      Address      Ports  Message
config-server/0*                      active    executing  10.1.245.33         Primary
config-server/1                       active    idle       10.1.245.34         
self-signed-certificates-separate/0*  active    idle       10.1.245.47         
self-signed-certificates/0*           active    idle       10.1.245.26         
shard-one/0*                          blocked   idle       10.1.245.40         Shard CA and Config-Server CA don't match.
shard-one/1                           blocked   idle       10.1.245.43         Shard CA and Config-Server CA don't match.
shard-one/2                           blocked   idle       10.1.245.42         Shard CA and Config-Server CA don't match.
shard-two/0*                          blocked   idle       10.1.245.46         Shard CA and Config-Server CA don't match.

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-shard-one-0: 01:39:20 ERROR unit.shard-one/0.juju-log database-peers:1: Charm is in sharding role: database. Does not support shard interface.
unit-shard-one-0: 01:39:26 ERROR unit.shard-one/0.juju-log database-peers:1: Charm is in sharding role: database. Does not support shard interface.
unit-config-server-1: 01:41:03 ERROR unit.config-server/1.juju-log config-server:3: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1728870062, 3), \'signature\': {\'hash\': b\'\\x7f\\x96\\x8c\\xcd\\xbb_\\xbc\\xfb\\x13g\\x85Kd\\xec\\xe4\\x08\\x15$\\x98\\xd5\', \'keyId\': 7425439791207940121}}, \'operationTime\': Timestamp(1728870062, 3)}')
unit-config-server-1: 01:41:04 ERROR unit.config-server/1.juju-log config-server:3: Failed to add shard-one to cluster
unit-config-server-1: 01:41:04 ERROR unit.config-server/1.juju-log config-server:3: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1728870062, 3), \'signature\': {\'hash\': b\'\\x7f\\x96\\x8c\\xcd\\xbb_\\xbc\\xfb\\x13g\\x85Kd\\xec\\xe4\\x08\\x15$\\x98\\xd5\', \'keyId\': 7425439791207940121}}, \'operationTime\': Timestamp(1728870062, 3)}')
unit-shard-one-1: 01:45:36 ERROR unit.shard-one/1.juju-log certificates:5: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-1: 01:45:37 ERROR unit.shard-one/1.juju-log certificates:5: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-two-0: 01:45:37 ERROR unit.shard-two/0.juju-log certificates:6: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 01:45:37 ERROR unit.shard-one/2.juju-log certificates:5: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 01:45:37 ERROR unit.config-server/0.juju-log certificates:7: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 01:45:37 ERROR unit.config-server/1.juju-log certificates:7: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 01:45:37 ERROR unit.shard-one/0.juju-log certificates:5: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 01:45:37 ERROR unit.config-server/1.juju-log certificates:7: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:45:37 ERROR unit.config-server/0.juju-log certificates:7: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-2: 01:45:37 ERROR unit.shard-one/2.juju-log certificates:5: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-0: 01:45:38 ERROR unit.shard-one/0.juju-log certificates:5: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-two-0: 01:45:38 ERROR unit.shard-two/0.juju-log certificates:6: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:45:45 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:45:45 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:46:00 ERROR unit.config-server/0.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:46:00 ERROR unit.config-server/0.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:46:12 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:46:12 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-shard-one-0: 01:46:49 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7808ee1e8fba4c53a15b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0022024250000640677>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0006370460000653111>]>
unit-shard-one-0: 01:46:52 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c780be770be126074b712, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.000742688999935126>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0016106310000623125>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0010221879999789962>]>
unit-shard-one-0: 01:46:55 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c780e37d3481b3335df91, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0015272030000232917>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.000711158999934014>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0008429449999312055>]>
unit-shard-one-0: 01:46:58 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c78101a57c8232eac8c06, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0009286550000524585>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0007381090000535551>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0006399960000180727>]>
unit-shard-one-0: 01:48:16 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:48:16 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:48:18 ERROR unit.shard-one/1.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:48:18 ERROR unit.shard-one/1.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-2: 01:48:39 ERROR unit.shard-one/2.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-2: 01:48:39 ERROR unit.shard-one/2.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:48:44 ERROR unit.shard-one/1.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:48:44 ERROR unit.shard-one/1.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:48:46 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:48:46 ERROR unit.shard-one/0.juju-log certificates:5: An unknown certificate is available -- ignoring.
unit-shard-two-0: 01:50:44 ERROR unit.shard-two/0.juju-log certificates:6: An unknown certificate is available -- ignoring.
unit-shard-two-0: 01:50:44 ERROR unit.shard-two/0.juju-log certificates:6: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:52:24 ERROR unit.config-server/0.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:52:24 ERROR unit.config-server/0.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:52:24 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:52:24 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 01:52:26 ERROR unit.config-server/1.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:52:26 ERROR unit.config-server/1.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:52:29 ERROR unit.config-server/1.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:52:29 ERROR unit.config-server/1.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:52:46 ERROR unit.config-server/0.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:52:47 ERROR unit.config-server/0.juju-log certificates:7: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:52:54 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:52:54 ERROR unit.config-server/0.juju-log certificates:7: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:55:01 ERROR unit.config-server/0.juju-log certificates:7: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:55:01 ERROR unit.config-server/0.juju-log certificates:7: This operation (delete_relation_data()) can only be performed by the leader unit
unit-self-signed-certificates-0: 01:55:11 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "b8048f6b-03ed-4250-8e97-0f6df7ea020e:r#6#shard-two": settings b8048f6b-03ed-4250-8e97-0f6df7ea020e:r#6#shard-two not found (not found)
unit-shard-two-0: 01:55:18 ERROR unit.shard-two/0.juju-log Unable to access primary due to: shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a05275f3394394d28e2, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-two-0.shard-two-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-shard-one-0: 01:55:18 ERROR unit.shard-one/0.juju-log Unable to access primary due to: shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a051542dbde9c630468, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-config-server-1: 01:55:20 ERROR unit.config-server/1.juju-log config-server:4: Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a07b05e3da39a7a9639, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-shard-one-0: 01:55:21 ERROR unit.shard-one/0.juju-log Unable to access primary due to: shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a0894ec77b580a59d6d, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-config-server-1: 01:55:23 ERROR unit.config-server/1.juju-log Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a0ac7a9d07be5a97b07, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-shard-two-0: 01:55:25 ERROR unit.shard-two/0.juju-log Unable to access primary due to: shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a0c326783fcbc010b78, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-two-0.shard-two-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-config-server-1: 01:55:25 ERROR unit.config-server/1.juju-log config-server:3: Deferring _on_relation_event for shards interface since: error=ServerSelectionTimeoutError("config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a0c8d860ad449944a10, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>")
unit-shard-two-0: 01:55:36 ERROR unit.shard-two/0.juju-log sharding:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 3319, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-shard-two-0/secret-get', '--label', 'sharding.4.extra.secret', '--refresh', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 3691, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 3321, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR consumer label "sharding.4.extra.secret" not found


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1657, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 45, in main
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/_main.py", line 515, in _emit
    self.framework.reemit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 867, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 605, in _handle_changed_secrets
    (operator_password, backup_password) = self.get_cluster_passwords(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 646, in get_cluster_passwords
    operator_password = self.database_requires.fetch_relation_field(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1350, in fetch_relation_field
    self.fetch_relation_data([relation_id], [field], relation_name)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1342, in fetch_relation_data
    data[relation.id] = self._fetch_specific_relation_data(relation, fields)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1818, in _fetch_specific_relation_data
    return self._fetch_relation_data_with_secrets(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1242, in _fetch_relation_data_with_secrets
    result, normal_fields = self._process_secret_fields(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1186, in _process_secret_fields
    if group_result := operation(relation, group, secret_fields, *args, **kwargs):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1120, in _get_group_secret_contents
    secret_data := secret.get_content()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 746, in get_content
    self._secret_content = self.meta.get_content(refresh=True)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 1462, in get_content
    self._content = self._backend.secret_get(id=self.id, label=self.label, refresh=refresh)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/model.py", line 3694, in secret_get
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError
unit-shard-two-0: 01:55:36 ERROR juju.worker.uniter.operation hook "sharding-relation-departed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:55:40 ERROR unit.shard-one/0.juju-log database-peers:1: Charm is in sharding role: database. Does not support shard interface.
unit-shard-one-0: 01:55:47 ERROR unit.shard-one/0.juju-log database-peers:1: Charm is in sharding role: database. Does not support shard interface.
unit-config-server-0: 01:55:48 ERROR unit.config-server/0.juju-log config-server/0.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a2249f45cd901625d13, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('config-server-0.config-server-endpoints', 27017) server_type: RSGhost, rtt: 0.008333463999861124>]>
unit-shard-one-1: 01:55:48 ERROR unit.shard-one/1.juju-log shard-one/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 670c7a23287e8ae2a4a2b0cb, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSGhost, rtt: 0.0016425679998519627>]>
unit-shard-one-2: 01:55:50 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "b8048f6b-03ed-4250-8e97-0f6df7ea020e:r#3#config-server": settings b8048f6b-03ed-4250-8e97-0f6df7ea020e:r#3#config-server not found (not found)
controller-0: 01:56:57 ERROR juju.worker.caasapplicationprovisioner.runner exited "shard-one": finding filesystem info for shard-one-mongodb-logs-5841dbe5: unable to get persistent volume claim: k8s: persistentvolumeclaims "shard-one-mongodb-logs-5841dbe5-shard-one-2" not found
controller-0: 01:57:02 ERROR juju.worker.caasapplicationprovisioner.runner exited "config-server": finding filesystem info for config-server-mongodb-logs-47408b3c: unable to get persistent volume claim: k8s: persistentvolumeclaims "config-server-mongodb-logs-47408b3c-config-server-1" not found
unit-shard-one-0: 01:58:53 ERROR unit.shard-one/0.juju-log database-peers:9: Charm is in sharding role: database. Does not support shard interface.
unit-shard-one-0: 01:58:59 ERROR unit.shard-one/0.juju-log database-peers:9: Charm is in sharding role: database. Does not support shard interface.
unit-shard-one-1: 01:59:32 ERROR unit.shard-one/1.juju-log certificates:11: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 01:59:32 ERROR unit.shard-one/2.juju-log certificates:11: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 01:59:32 ERROR unit.shard-one/0.juju-log certificates:11: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-two-0: 01:59:32 ERROR unit.shard-two/0.juju-log certificates:12: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 01:59:32 ERROR unit.shard-one/0.juju-log certificates:11: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-1: 01:59:33 ERROR unit.shard-one/1.juju-log certificates:11: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-2: 01:59:33 ERROR unit.shard-one/2.juju-log certificates:11: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:59:33 ERROR unit.config-server/0.juju-log certificates:13: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 01:59:33 ERROR unit.config-server/1.juju-log certificates:13: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-two-0: 01:59:34 ERROR unit.shard-two/0.juju-log certificates:12: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:59:34 ERROR unit.config-server/0.juju-log certificates:13: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 01:59:34 ERROR unit.config-server/1.juju-log certificates:13: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 02:01:06 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=9a30def6-21f6-4889-ada9-dbd333b18b6e,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=9a30def6-21f6-4889-ada9-dbd333b18b6e,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1728871266, 1), \'signature\': {\'hash\': b\'\\xeah\\xa2x[\\x07=\\xf8\\x87\\xf1q\\xbd\\xc1@\\x1cG?\\x19\\xaa\\x9c\', \'keyId\': 7425444820614643737}}, \'operationTime\': Timestamp(1728871265, 1)}')
unit-config-server-0: 02:01:06 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard-one to cluster
unit-config-server-0: 02:01:06 ERROR unit.config-server/0.juju-log config-server:14: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=9a30def6-21f6-4889-ada9-dbd333b18b6e,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=9a30def6-21f6-4889-ada9-dbd333b18b6e,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1728871266, 1), \'signature\': {\'hash\': b\'\\xeah\\xa2x[\\x07=\\xf8\\x87\\xf1q\\xbd\\xc1@\\x1cG?\\x19\\xaa\\x9c\', \'keyId\': 7425444820614643737}}, \'operationTime\': Timestamp(1728871265, 1)}')
unit-shard-one-1: 02:01:20 ERROR unit.shard-one/1.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-1: 02:01:20 ERROR unit.shard-one/1.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-0: 02:01:22 ERROR unit.shard-one/0.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-0: 02:01:22 ERROR unit.shard-one/0.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-config-server-0: 02:01:23 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1728871282, 1), \'signature\': {\'hash\': b\'\\x8bd\\x85c\\xda\\x82\\xfbO\\x04-\\x17}\\xb4\\xe7gUa\\x03XN\', \'keyId\': 7425444820614643737}}, \'operationTime\': Timestamp(1728871282, 1)}')
unit-config-server-0: 02:01:23 ERROR unit.config-server/0.juju-log config-server:14: Failed to add shard-one to cluster
unit-config-server-0: 02:01:23 ERROR unit.config-server/0.juju-log config-server:14: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1728871282, 1), \'signature\': {\'hash\': b\'\\x8bd\\x85c\\xda\\x82\\xfbO\\x04-\\x17}\\xb4\\xe7gUa\\x03XN\', \'keyId\': 7425444820614643737}}, \'operationTime\': Timestamp(1728871282, 1)}')
unit-shard-one-2: 02:01:25 ERROR unit.shard-one/2.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-2: 02:01:25 ERROR unit.shard-one/2.juju-log certificates:11: An unknown certificate is available -- ignoring.
unit-shard-one-0: 02:01:39 ERROR unit.shard-one/0.juju-log Failed changing the password: The server is in quiesce mode and will shut down, full error: {'topologyVersion': {'processId': ObjectId('670c7b76107929ce7e4fc27a'), 'counter': 11}, 'ok': 0.0, 'errmsg': 'The server is in quiesce mode and will shut down', 'code': 91, 'codeName': 'ShutdownInProgress', 'remainingQuiesceTimeMillis': 14951, 'lastCommittedOpTime': Timestamp(1728871299, 6), '$clusterTime': {'clusterTime': Timestamp(1728871299, 13), 'signature': {'hash': b'\x90q\x9c\x1cK\xbcQ\x07\x8b\x89\xc1l$\xd1\x8c\xe0KB\xd4G', 'keyId': 7425444820614643737}}, 'operationTime': Timestamp(1728871299, 6)}
unit-config-server-0: 02:01:51 ERROR unit.config-server/0.juju-log config-server:15: Failed to add shard shard-two to the config server, error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=9a30def6-21f6-4889-ada9-dbd333b18b6e,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=9a30def6-21f6-4889-ada9-dbd333b18b6e,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1728871310, 1), \'signature\': {\'hash\': b\'v8j[@\\x96\\xecNu\\xbe\\x80Vf\\xb9\\x8f\\x89c]\\xeb\\xa9\', \'keyId\': 7425444820614643737}}, \'operationTime\': Timestamp(1728871310, 1)}')
unit-config-server-0: 02:01:51 ERROR unit.config-server/0.juju-log config-server:15: Failed to add shard-two to cluster
unit-config-server-0: 02:01:51 ERROR unit.config-server/0.juju-log config-server:15: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=9a30def6-21f6-4889-ada9-dbd333b18b6e,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=9a30def6-21f6-4889-ada9-dbd333b18b6e,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1728871310, 1), \'signature\': {\'hash\': b\'v8j[@\\x96\\xecNu\\xbe\\x80Vf\\xb9\\x8f\\x89c]\\xeb\\xa9\', \'keyId\': 7425444820614643737}}, \'operationTime\': Timestamp(1728871310, 1)}')
unit-shard-two-0: 02:02:05 ERROR unit.shard-two/0.juju-log certificates:12: An unknown certificate is available -- ignoring.
unit-shard-two-0: 02:02:05 ERROR unit.shard-two/0.juju-log certificates:12: An unknown certificate is available -- ignoring.
unit-shard-one-0: 02:06:09 ERROR unit.shard-one/0.juju-log certificates:16: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 02:06:09 ERROR unit.shard-one/0.juju-log certificates:16: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-2: 02:07:10 ERROR unit.shard-one/2.juju-log certificates:16: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 02:07:10 ERROR unit.shard-one/2.juju-log certificates:16: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-1: 02:07:15 ERROR unit.shard-one/1.juju-log certificates:16: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-1: 02:07:15 ERROR unit.shard-one/1.juju-log certificates:16: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 02:11:21 ERROR unit.config-server/1.juju-log certificates:13: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:11:21 ERROR unit.config-server/1.juju-log certificates:13: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:13:23 ERROR unit.config-server/1.juju-log certificates:17: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 02:13:24 ERROR unit.config-server/1.juju-log certificates:17: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 02:13:24 ERROR unit.config-server/0.juju-log certificates:17: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 02:13:24 ERROR unit.config-server/0.juju-log certificates:17: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 02:13:28 ERROR unit.config-server/1.juju-log certificates:17: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:13:28 ERROR unit.config-server/1.juju-log certificates:17: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:13:43 ERROR unit.config-server/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:13:43 ERROR unit.config-server/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:13:53 ERROR unit.config-server/1.juju-log certificates:17: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:13:53 ERROR unit.config-server/1.juju-log certificates:17: This operation (update_relation_data()) can only be performed by the leader unit
unit-shard-one-1: 02:15:43 ERROR unit.shard-one/1.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-shard-one-0: 02:15:49 ERROR unit.shard-one/0.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-shard-two-0: 02:15:51 ERROR unit.shard-two/0.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-shard-one-2: 02:15:52 ERROR unit.shard-one/2.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...